##
## Copyright (c) 2019-2025
## Pertti Palo, Scott Moisik, Matthew Faytak, and Motoki Saito.
##
## This file is part of Speech Articulation ToolKIT
## (see https://github.com/giuthas/satkit/).
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program. If not, see <http://www.gnu.org/licenses/>.
##
## The example data packaged with this program is licensed under the
## Creative Commons Attribution-NonCommercial-ShareAlike 4.0
## International (CC BY-NC-SA 4.0) License. You should have received a
## copy of the Creative Commons Attribution-NonCommercial-ShareAlike 4.0
## International (CC BY-NC-SA 4.0) License along with the data. If not,
## see <https://creativecommons.org/licenses/by-nc-sa/4.0/> for details.
##
## When using the toolkit for scientific publications, please cite the
## articles listed in README.markdown. They can also be found in
## citations.bib in BibTeX format.
##
import_config:
  # Single spline file for all recordings (True) or one for each recording
  # (False).
  single_spline_file: False

  # Only one of the following will be in use.
  # If a single spline file, what is it called.
  spline_file: File003_splines.csv
  # If not a single spline, what glob pattern should be used to find the splines.
  # E.g. '*.csv'
  spline_file_extension: '_splines.csv'

  # Do the files have a header row?
  # Please note that possible header row information is ignored.
  headers: True

  # What delimiter does the file use. If left empty, this defaults to a tabulator.
  delimiter:

  # Either 'polar' or 'Cartesian' 
  coordinates: polar

  # Are the coordinates interleaved in 
  #  interleaved format (True): point1/x point1/y point2/x point2/y
  #  or non-interleaved (False): point1/x point2/x ... point1/y point2/y
  interleaved_coords: False

  # These are listed in order of appearance in the file. 
  # Please note that possible header row information is ignored.
  # Accepted values:
    # - ignore: marks a column to be ignored, unlike the others below, 
    #   can be used several times
    # - id: used to identify the speaker, 
    #   often contained in a csv field called 'family name'
    # - given names: appended to 'id' if not marked 'ignore'
    # - date and time: dat3 and time of recording
    # - prompt: prompt of recording, used to identify the recording with 'id'
    # - annotation label: optional field containing annotation information
    # - time in recording: timestamp of the frame this spline belongs to
    # - number of spline points: number of sample points in the spline used 
    #   to parse the coordinates and possible confidence information
  meta_columns:
    - id
    - date and time
    - time in recording
    - prompt
    - number of spline points

  # These will be either interleaved or not as specified by 'interleaved coords'.
  # Confidence values are always assumed to be non-interleaved.
  # Accepted values: 'r' with 'phi', 'x' with 'y', and 'confidence'
  data_columns:
    - r
    - phi
    - confidence

data_config:
  # How many points should be ignored at the front and at the end of a spline.
  # All of the data is always read in, This setting is used in plotting and
  # processing the splines. Defaults to 0 at front and 0 at back if not specified:
  # ignore_points:
  #   - 0
  #   - 0
  ignore_points:
  - 11
  - 0
