##
## Copyright (c) 2019-2024
## Pertti Palo, Scott Moisik, Matthew Faytak, and Motoki Saito.
##
## This file is part of Speech Articulation ToolKIT
## (see https://github.com/giuthas/satkit/).
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program. If not, see <http://www.gnu.org/licenses/>.
##
## The example data packaged with this program is licensed under the
## Creative Commons Attribution-NonCommercial-ShareAlike 4.0
## International (CC BY-NC-SA 4.0) License. You should have received a
## copy of the Creative Commons Attribution-NonCommercial-ShareAlike 4.0
## International (CC BY-NC-SA 4.0) License along with the data. If not,
## see <https://creativecommons.org/licenses/by-nc-sa/4.0/> for details.
##
## When using the toolkit for scientific publications, please cite the
## articles listed in README.markdown. They can also be found in
## citations.bib in BibTeX format.
##


# Please note that empty file or directory fields are interpreted as not
# available and represented by None. If you want to specify current working
# directory, use '.'

# What precision is treated as equal when comparing annotation boundaries.
epsilon: 0.00001

# Used in filtering sound signals before beep detection.
mains_frequency: 50

# Default parameters for a data run. Unless you happen to be running example
# tongue data, you should probably change these. Do it by copying the file and
# giving a commandline argument.
data_run_parameter_file: configuration/satkit_data_run_parameters.yaml

# GUI setup parameters
gui_parameter_file: configuration/satkit_gui_parameters.yaml

publish_parameter_file: configuration/satkit_publish_parameters.yaml